trainer: imgrec_trainer

train_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: celeba
      args: {root_path: $load_root$/trans-nf/celeba, split: train}
    width: 178
  loader:
    batch_size: 16
    num_workers: 8

test_dataset:
  name: imgrec_dataset
  args:
    imageset:
      name: celeba
      args: {root_path: $load_root$/trans-nf/celeba, split: test}
    width: 178
  loader:
    batch_size: 16
    num_workers: 8

model:
  name: trans_nf
  args:
    tokenizer:
      name: imgrec_tokenizer
      args: {input_size: 178, patch_size: 9, padding: 1}
    hyponet:
      name: hypo_mlp
      args: {in_dim: 2, out_dim: 3, depth: 5, hidden_dim: 256, use_pe: true, pe_dim: 128}
    n_groups: 64
    transformer_encoder:
      name: transformer_encoder
      args: {dim: 512, depth: 6, n_head: 8, head_dim: 64, ff_dim: 2048}

optimizer:
  name: adam
  args: {lr: 1.e-4}
max_epoch: 30

eval_epoch: 1
vis_epoch: 5
